[workspace]
resolver = "2"

members = [
    "vhost-device-gpio",
    "vhost-device-i2c",
    "vhost-device-rng",
    "vhost-device-scsi",
    "vhost-device-scmi",
    "crates/sound",
    "vhost-device-vsock",
]
